=begin
#Repull API

#The unified API for vacation rental tech. Connect to 50+ PMS platforms and 4 OTA channels through one REST API. Built-in AI operations for guest communication, pricing, and listing optimization.  ## Quick Start 1. Get an API key at https://repull.dev/dashboard 2. Connect a PMS: `POST /v1/connect/{provider}` 3. List properties: `GET /v1/properties` 4. Get reservations: `GET /v1/reservations`  ## Authentication All requests require a Bearer token: ``` Authorization: Bearer sk_test_YOUR_API_KEY ```  Sandbox keys start with `sk_test_`, production with `sk_live_`.

The version of the OpenAPI document: 1.0.0
Contact: ivan@vanio.ai
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Repull::AirbnbApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AirbnbApi' do
  before do
    # run before each test
    @api_instance = Repull::AirbnbApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AirbnbApi' do
    it 'should create an instance of AirbnbApi' do
      expect(@api_instance).to be_instance_of(Repull::AirbnbApi)
    end
  end

  # unit tests for v1_channels_airbnb_listings_get
  # List Airbnb listings
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_listings_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_listings_id_availability_get
  # Get Airbnb availability
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_listings_id_availability_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_listings_id_availability_put
  # Update Airbnb availability
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_listings_id_availability_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_listings_id_get
  # Get Airbnb listing
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_listings_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_listings_id_photos_get
  # List Airbnb photos
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_listings_id_photos_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_listings_id_photos_post
  # Upload photos to Airbnb
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_listings_id_photos_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_listings_id_post
  # Listing action (push/publish/unlist/delete)
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_listings_id_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_listings_id_pricing_get
  # Get Airbnb pricing
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_listings_id_pricing_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_listings_id_pricing_put
  # Update Airbnb pricing
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_listings_id_pricing_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_listings_post
  # Create/push Airbnb listing
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_listings_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_messaging_get
  # List Airbnb message threads
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_messaging_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_messaging_thread_id_messages_get
  # Get Airbnb messages
  # @param thread_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_messaging_thread_id_messages_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_messaging_thread_id_messages_post
  # Send Airbnb message
  # @param thread_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_messaging_thread_id_messages_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_reservations_code_get
  # Get Airbnb reservation
  # @param code 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_reservations_code_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_reservations_code_post
  # Accept/decline/cancel Airbnb reservation
  # @param code 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_reservations_code_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_reservations_get
  # List Airbnb reservations
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_reservations_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_reviews_get
  # List Airbnb reviews
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_reviews_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_reviews_post
  # Respond to Airbnb review
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_reviews_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_airbnb_sync_post
  # Bulk sync to Airbnb
  # Push all property data to Airbnb in one call.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_airbnb_sync_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
