=begin
#Repull API

#The unified API for vacation rental tech. Connect to 50+ PMS platforms and 4 OTA channels through one REST API. Built-in AI operations for guest communication, pricing, and listing optimization.  ## Quick Start 1. Get an API key at https://repull.dev/dashboard 2. Connect a PMS: `POST /v1/connect/{provider}` 3. List properties: `GET /v1/properties` 4. Get reservations: `GET /v1/reservations`  ## Authentication All requests require a Bearer token: ``` Authorization: Bearer sk_test_YOUR_API_KEY ```  Sandbox keys start with `sk_test_`, production with `sk_live_`.

The version of the OpenAPI document: 1.0.0
Contact: hello@repull.dev
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Repull::PlumguideApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PlumguideApi' do
  before do
    # run before each test
    @api_instance = Repull::PlumguideApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PlumguideApi' do
    it 'should create an instance of PlumguideApi' do
      expect(@api_instance).to be_instance_of(Repull::PlumguideApi)
    end
  end

  # unit tests for v1_channels_plumguide_availability_get
  # Get Plumguide availability
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_plumguide_availability_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_plumguide_availability_put
  # Push availability to Plumguide
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_plumguide_availability_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_plumguide_listings_get
  # List Plumguide listings
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_plumguide_listings_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_plumguide_pricing_get
  # Get Plumguide pricing
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_plumguide_pricing_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_channels_plumguide_pricing_put
  # Push pricing to Plumguide
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_channels_plumguide_pricing_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
