=begin
#Repull API

#The unified API for vacation rental tech. Connect to 50+ PMS platforms and 4 OTA channels through one REST API. Built-in AI operations for guest communication, pricing, and listing optimization.  ## Quick Start 1. Get an API key at https://repull.dev/dashboard 2. Connect a PMS: `POST /v1/connect/{provider}` 3. List properties: `GET /v1/properties` 4. Get reservations: `GET /v1/reservations`  ## Authentication All requests require a Bearer token: ``` Authorization: Bearer sk_test_YOUR_API_KEY ```  Sandbox keys start with `sk_test_`, production with `sk_live_`.

The version of the OpenAPI document: 1.0.0
Contact: ivan@vanio.ai
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Repull::V1WebhooksTestPostRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Repull::V1WebhooksTestPostRequest do
  #let(:instance) { Repull::V1WebhooksTestPostRequest.new }

  describe 'test an instance of V1WebhooksTestPostRequest' do
    it 'should create an instance of V1WebhooksTestPostRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Repull::V1WebhooksTestPostRequest)
    end
  end

  describe 'test attribute "webhook_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "event"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
