=begin
#Repull API

#The unified API for vacation rental tech. Connect to 50+ PMS platforms and 4 OTA channels through one REST API. Built-in AI operations for guest communication, pricing, and listing optimization.  ## Quick Start 1. Get an API key at https://repull.dev/dashboard 2. Connect a PMS: `POST /v1/connect/{provider}` 3. List properties: `GET /v1/properties` 4. Get reservations: `GET /v1/reservations`  ## Authentication All requests require a Bearer token: ``` Authorization: Bearer sk_test_YOUR_API_KEY ```  Sandbox keys start with `sk_test_`, production with `sk_live_`.

The version of the OpenAPI document: 1.0.0
Contact: hello@repull.dev
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

# Common files
require 'repull/api_client'
require 'repull/api_error'
require 'repull/api_model_base'
require 'repull/version'
require 'repull/configuration'

# Models
require 'repull/models/ai_operation'
require 'repull/models/calendar_day'
require 'repull/models/connect_host'
require 'repull/models/connect_status'
require 'repull/models/connection'
require 'repull/models/conversation'
require 'repull/models/error'
require 'repull/models/error_error'
require 'repull/models/guest'
require 'repull/models/message'
require 'repull/models/paginated_response'
require 'repull/models/paginated_response_pagination'
require 'repull/models/property'
require 'repull/models/reservation'
require 'repull/models/v1_ai_post200_response'
require 'repull/models/v1_availability_property_id_get200_response'
require 'repull/models/v1_availability_property_id_put_request'
require 'repull/models/v1_billing_post_request'
require 'repull/models/v1_connect_get200_response'
require 'repull/models/v1_connect_provider_post_request'
require 'repull/models/v1_conversations_get200_response'
require 'repull/models/v1_conversations_id_messages_get200_response'
require 'repull/models/v1_conversations_id_messages_post_request'
require 'repull/models/v1_guests_get200_response'
require 'repull/models/v1_health_get200_response'
require 'repull/models/v1_properties_get200_response'
require 'repull/models/v1_reservations_get200_response'
require 'repull/models/v1_reservations_id_patch_request'
require 'repull/models/v1_reservations_post_request'
require 'repull/models/v1_webhooks_get200_response'
require 'repull/models/v1_webhooks_post_request'
require 'repull/models/v1_webhooks_test_post_request'
require 'repull/models/webhook_subscription'

# APIs
require 'repull/api/ai_api'
require 'repull/api/airbnb_api'
require 'repull/api/availability_api'
require 'repull/api/billing_api'
require 'repull/api/booking_com_api'
require 'repull/api/connect_api'
require 'repull/api/conversations_api'
require 'repull/api/guests_api'
require 'repull/api/plumguide_api'
require 'repull/api/properties_api'
require 'repull/api/reservations_api'
require 'repull/api/system_api'
require 'repull/api/vrbo_api'
require 'repull/api/webhooks_api'

module Repull
  class << self
    # Customize default settings for the SDK using block.
    #   Repull.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
